### ISSUE TITLE
Replace test case with coarser resolution 

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [ClaraDraper-NOAA/IMSobsproc#3]
Intention is to use a resolution that matches the IODA test case. Either C48, or c6 : waiting on response from Cory.

**Comment by YoulongXia-NOAA** [comment]
C48 should be fine as Cory said.

**Comment by ClaraDraper-NOAA** [comment]
C48 test case is now at: 

/scratch2/BMC/gsienkf/Clara.Draper/DA_test_cases/snow/fIMS
