### ISSUE TITLE
IMS snow cover with ascii and tif fromat

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [ClaraDraper-NOAA/IMSobsproc#5]
Edited after some discussion: 
Youlong has identified some aspects of the input data that will need to be changed for use at EMC.

1. For the IMS observations, we're using tif files converted to .nc, then reading them in with python. For operations, it would be better to download an ascii file and read it straight into fortran. 

2. When calculating the IMS index file, we're currently reading the x,y info from an IMS data file, and projecting it to get lat/lon info, which creates a dependency on our assumed projection. It would be better to use the lat/lon meta data provided as static files with the IMS (or maybe, use the same projection tools as are currently used in UFS_UTILS).

Youlong's original issue:
IMSaggregate_asciiInput_mod.f90 is strongly depended on the different format IMS files. Here it depends on IMS index file and converted IMS nc file from tif format besides FV3 CXX.  Additionally, IMS index file are also calculated from the converted IMS nc file using Python code. The number of lon is 8703 and and the number of lat is 2716.  This code cannot directly use IMS ascii file as its lon and lat are 6144, respectively. 

Therefore, from operational viewpoint, you first need to download IMS tif file, and then using python code to convert it into nc file. For the given FV3 Cxx, e.g., C96, index file is a one-time work. 

Is there is a chance to directly use IMS ascii files or ioda ims nc file as both data size is 6144X6144?

**Comment by YoulongXia-NOAA** [comment]
I want to add Tsga to this discussion but I cannot add him. Perhaps you need to send an invitation to him?

**Comment by YoulongXia-NOAA** [comment]
I think that you used gdal to re-gridded  original IMS snow cover with 6144 x 6144 data size to 8703 x 2716 size to develop your code rather than use original data directly. This may be okay for research purpose but not for operational purpose, right? In future, we need to consider to use original data directly to your framework.

**Comment by YoulongXia-NOAA** [comment]
I want to modify your code to read original ascii IMS file or the converted 4km ascii file from 1km IMS ascii file. After I take a look, it is not possible as your code is developed based on gdal processed nc file, e.g., index files, and input 2-D IMS array is for 8703 x 2716. When I used my 6144 X 6144 IMS data, it will mismatch your index file. Therefore, I need to recalculate the index file using 6144 X 6144 array including IMS snow cover, lat, and lon. I am not sure if I will need to do that.

**Comment by ClaraDraper-NOAA** [comment]
> I want to modify your code to read original ascii IMS file or the converted 4km ascii file from 1km IMS ascii file. After I take a look, it is not possible as your code is developed based on gdal processed nc file, e.g., index files, and input 2-D IMS array is for 8703 x 2716. When I used my 6144 X 6144 IMS data, it will mismatch your index file. Therefore, I need to recalculate the index file using 6144 X 6144 array including IMS snow cover, lat, and lon. I am not sure if I will need to do that.

@YoulongXia-NOAA Today I will look at the script for the index generation, and add the lat/lon to the output among other things. 


> IMSaggregate_asciiInput_mod.f90 is strongly depended on the different format IMS files. Here it depends on IMS index file and converted IMS nc file from tif format besides FV3 CXX. Additionally, IMS index file are also calculated from the converted IMS nc file using Python code. The number of lon is 8703 and and the number of lat is 2716. This code cannot directly use IMS ascii file as its lon and lat are 6144, respectively.
> 
> Therefore, from operational viewpoint, you first need to download IMS tif file, and then using python code to convert it into nc file. For the given FV3 Cxx, e.g., C96, index file is a one-time work.
> 
> Is there is a chance to directly use IMS ascii files or ioda ims nc file as both data size is 6144X6144?

@tsga can you comment on this? Perhaps we should have a quick phone call this afternoon, once you're back at work?

**Comment by tsga** [comment]
Seems the problem (change in the number of grid cells) was caused by the projection I did (to WGS84) 
gdalwarp -t_srs EPSG:4326  -te -180.0 0.0 180.0 90.0 -r near  -overwrite -of netCDF ims2019319_4km_GIS_v1.3.tif wgs_ims2019319_4km_GIS_v1.3.tif.nc

Possible solutions can be:
- We may be able to convert the input IMS to netCDF  in its native Polar Stereographic projection and that keeps the grid cells configuration intact; then prepare the Index files again for this projection. 
- Make the projection to WGS84 part of the workflow

**Comment by ClaraDraper-NOAA** [comment]
Summary of meeting with @tsga  and @YoulongXia-NOAA: 

There are three aspects we need to address: 
1. Format of the input IMS data files. We need to replace the current approach of downloading tif, and converting to netcdf, with directly using whichever file format is downloaded. 

ACTION: @YoulongXia-NOAA to follow up with George, and look into adopting the current approach / using available tools. 

2. Lat/lon info used in to generated the index file. We should not be projecting it ourselves, and instead use the lat/lon in the meta data files provided by the data providers. 

ACTION: @YoulongXia-NOAA to follow up with George, and look into adopting the current approach / using available tools. 

3. We also discussed improving the method used to allocate IMS observations to the model grid cells. I will create a separate issue for that. 

> IMSaggregate_asciiInput_mod.f90 is strongly depended on the different format IMS files. Here it depends on IMS index file and converted IMS nc file from tif format besides FV3 CXX. Additionally, IMS index file are also calculated from the converted IMS nc file using Python code. The number of lon is 8703 and and the number of lat is 2716. This code cannot directly use IMS ascii file as its lon and lat are 6144, respectively.
> 
> Therefore, from operational viewpoint, you first need to download IMS tif file, and then using python code to convert it into nc file. For the given FV3 Cxx, e.g., C96, index file is a one-time work.
> 
> Is there is a chance to directly use IMS ascii files or ioda ims nc file as both data size is 6144X6144?

**Comment by YoulongXia-NOAA** [comment]
George's response is below: Current GFS OPS uses a two step method. First, all snow data is interpolated to a gaussian lat/lon grid. Then, global_cycle interpolates the snow from the gaussian grid to the FV3 grid.

**Comment by YoulongXia-NOAA** [comment]
For IMS lat/lon, his response is below: 

You can use the NCEPLIBS IP library to compute the lat/lon for the IMS grid. Clara is familiar with how to do that as she recently wrote code to interpolate land increments to the fv3 grid:

UFS_UTILS/land_increments.f90 at develop · NOAA-EMC/UFS_UTILS (github.com)

The call to gdswzd computes the lat/lons. **The first argument - KGDS - holds the grib1 grid description section information for the IMS grid. The KGDS array is returned by a previous call to the grib1 W3 library**. (Use grib1 W3 library to create lat/lon information)

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA has completed this, and we're now using the ascii files.
